# the site's base url
baseURL = 'https://www.davelongwebstudio.com/'

# the site's language code
languageCode = 'en-us'

# the site's title
title = 'Dave Long Web Studio'

# the site's main description
description = 'Building Web Sites: Web Development & Design, Content Generation, Copywriting, SEO & Performance Optimization, Accessibility.'
# custom parameters
[params] 
  description = 'home page description'

# menu items
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 20

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 30

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 40

# allow markup to include html elements
[markup.goldmark.renderer]
  unsafe = true

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = 0
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = 0
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = 0
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = 0
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = 0
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = 0
