# the site's base url
baseURL = 'https://www.davelongwebstudio.com/'

# the site's language code
languageCode = 'en-us'

# the site's title
title = 'Dave Long Web Studio'

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 20

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 30

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 40

  [markup.goldmark.renderer]
  unsafe = true
